title: Temporal Dead Zone
description: Songzi Alexander Vong's homepage and blog.
url: https://songzivong.github.io
author: Songzi Alexander Vong
email: songzivong@gmail.com

theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: songzivong
    rss: feed

header_pages:
  - about.md
  - categories.md
  - tags.md

disqus:
  shortname: songzivong

google_analytics: UA-138501173-1

show_excerpts: true
